[metadata.heroku]
  root-package = "github.com/republicprotocol/ingress-heroku-go"
  go-version = "1.10.2"
  install = "./cmd/ingress"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.10"

[[constraint]]
  branch = "f∅"
  name = "github.com/republicprotocol/republic-go"

[prune]
  go-tests = true