[metadata.heroku]
  go-version = "1.10.4"
  root-package = "github.com/republicprotocol/renex-ingress-go"
  install = "./cmd/ingress"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.8.12"

[[constraint]]
  name = "github.com/republicprotocol/republic-go"
  branch = "master"

# Fix to resolve dependency issues within go-ethereum
[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

# Temporary fix https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
