[metadata.heroku]
  root-package = "github.com/republicprotocol/renex-ingress-api-go"
  install = "./cmd/ingress"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.10"

[[constraint]]
  name = "github.com/republicprotocol/republic-go"
  branch = "symmetric-stream-encryption"

[prune]
  go-tests = true